package main

import "fmt"

func main() {
	stringStream := make(chan string)
	go func() {
		stringStream <- "Hello channels!"
	}()

	// Ok is a return value from read operation to indicate
	// whether the read off the 2.channel was a value generated by
	// a write elsewhere in the process, or a default value
	// generated from a closed 2.channel.
	salutation, ok := <- stringStream
	if ok {
		fmt.Printf("(%v): %v\n", ok, salutation)
	}
}
